#!/usr/bin/env bash

set -e

payload='{
  "batchId": "1234",
  "department": "foo",
  "address": {
    "name": "test",
    "street": "test",
    "postalCode": "99999",
    "city": "test"
  },
  "content": ["test"],
  "attachments": [
    {
      "name": "test.pdf",
      "contentType": "application/pdf",
      "content": "JVBERi0xLjQgCjEgMCBvYmoKPDwKL1BhZ2VzIDIgMCBSCi9UeXBlIC9DYXRhbG9nCj4+CmVuZG9iagoyIDAgb2JqCjw8Ci9UeXBlIC9QYWdlcwovS2lkcyBbIDMgMCBSIF0KL0NvdW50IDEKPj4KZW5kb2JqCjMgMCBvYmoKPDwKL1R5cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgovUmVzb3VyY2VzIDw8Ci9YT2JqZWN0IDw8IC9JbTAgOCAwIFIgPj4KL1Byb2NTZXQgNiAwIFIgPj4KL01lZGlhQm94IFswIDAgNTk1IDg0Ml0KL0Nyb3BCb3ggWzAgMCA1OTUgODQyXQovQ29udGVudHMgNCAwIFIKL1RodW1iIDExIDAgUgo+PgplbmRvYmoKNCAwIG9iago8PAovTGVuZ3RoIDUgMCBSCj4+CnN0cmVhbQpxCjEgMCAwIDEgMCAwIGNtCi9JbTAgRG8KUQoKZW5kc3RyZWFtCmVuZG9iago1IDAgb2JqCjI3CmVuZG9iago2IDAgb2JqClsgL1BERiAvVGV4dCAvSW1hZ2VDIF0KZW5kb2JqCjcgMCBvYmoKPDwKPj4KZW5kb2JqCjggMCBvYmoKPDwKL1R5cGUgL1hPYmplY3QKL1N1YnR5cGUgL0ltYWdlCi9OYW1lIC9JbTAKL0ZpbHRlciBbIC9SdW5MZW5ndGhEZWNvZGUgXQovV2lkdGggMQovSGVpZ2h0IDEKL0NvbG9yU3BhY2UgMTAgMCBSCi9CaXRzUGVyQ29tcG9uZW50IDgKL1NNYXNrIDE1IDAgUgovTGVuZ3RoIDkgMCBSCj4+CnN0cmVhbQoAAIAKZW5kc3RyZWFtCmVuZG9iago5IDAgb2JqCjMKZW5kb2JqCjEwIDAgb2JqCi9EZXZpY2VHcmF5CmVuZG9iagoxMSAwIG9iago8PAovRmlsdGVyIFsgL1J1bkxlbmd0aERlY29kZSBdCi9XaWR0aCAxCi9IZWlnaHQgMQovQ29sb3JTcGFjZSAxMCAwIFIKL0JpdHNQZXJDb21wb25lbnQgOAovTGVuZ3RoIDEyIDAgUgo+PgpzdHJlYW0KAACACmVuZHN0cmVhbQplbmRvYmoKMTIgMCBvYmoKMwplbmRvYmoKMTMgMCBvYmoKPDwKPj4KZW5kb2JqCjE0IDAgb2JqCjMKZW5kb2JqCjE1IDAgb2JqCjw8Ci9UeXBlIC9YT2JqZWN0Ci9TdWJ0eXBlIC9JbWFnZQovTmFtZSAvTWEwCi9GaWx0ZXIgWyAvUnVuTGVuZ3RoRGVjb2RlIF0KL1dpZHRoIDEKL0hlaWdodCAxCi9Db2xvclNwYWNlIC9EZXZpY2VHcmF5Ci9CaXRzUGVyQ29tcG9uZW50IDgKL0xlbmd0aCAxNiAwIFIKPj4Kc3RyZWFtCgAAgAplbmRzdHJlYW0KZW5kb2JqCjE2IDAgb2JqCjMKZW5kb2JqCjE3IDAgb2JqCjw8Ci9UaXRsZSA8RkVGRjAwNjE+Ci9BdXRob3IgPEZFRkYwMDY4MDA3NDAwNzQwMDcwMDA3MzAwM0EwMDJGMDAyRjAwNjkwMDZEMDA2MTAwNjcwMDY1MDA2RDAwNjEwMDY3MDA2OTAwNjMwMDZCMDAyRTAwNkYwMDcyMDA2Nz4KL0NyZWF0b3IgPEZFRkYwMDY4MDA3NDAwNzQwMDcwMDA3MzAwM0EwMDJGMDAyRjAwNjkwMDZEMDA2MTAwNjcwMDY1MDA2RDAwNjEwMDY3MDA2OTAwNjMwMDZCMDAyRTAwNkYwMDcyMDA2Nz4KL1Byb2R1Y2VyIDxGRUZGMDA2ODAwNzQwMDc0MDA3MDAwNzMwMDNBMDAyRjAwMkYwMDY5MDA2RDAwNjEwMDY3MDA2NTAwNkQwMDYxMDA2NzAwNjkwMDYzMDA2QjAwMkUwMDZGMDA3MjAwNjc+Ci9DcmVhdGlvbkRhdGUgKEQ6MjAyNTA3MzAxNzMyMjQpCi9Nb2REYXRlIChEOjIwMjUwNzMwMTczMjI0KQo+PgplbmRvYmoKeHJlZgowIDE4CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAxMCAwMDAwMCBuIAowMDAwMDAwMDU5IDAwMDAwIG4gCjAwMDAwMDAxMTggMDAwMDAgbiAKMDAwMDAwMDMwMCAwMDAwMCBuIAowMDAwMDAwMzgwIDAwMDAwIG4gCjAwMDAwMDAzOTggMDAwMDAgbiAKMDAwMDAwMDQzNiAwMDAwMCBuIAowMDAwMDAwNDU3IDAwMDAwIG4gCjAwMDAwMDA2NTYgMDAwMDAgbiAKMDAwMDAwMDY3MyAwMDAwMCBuIAowMDAwMDAwNzAxIDAwMDAwIG4gCjAwMDAwMDA4NDYgMDAwMDAgbiAKMDAwMDAwMDg2NCAwMDAwMCBuIAowMDAwMDAwODg2IDAwMDAwIG4gCjAwMDAwMDA5MDQgMDAwMDAgbiAKMDAwMDAwMTA5NiAwMDAwMCBuIAowMDAwMDAxMTE0IDAwMDAwIG4gCnRyYWlsZXIKPDwKL1NpemUgMTgKL0luZm8gMTcgMCBSCi9Sb290IDEgMCBSCj4+CnN0YXJ0eHJlZgoxNTM5CiUlRU9GCg=="
    }
  ]
}'

pids=()

base_url=http://app:8080

for _ in {1..5}; do
  echo "sending post to ${base_url}/2281/send/snailmail..."
  curl -fs -X POST "${base_url}/2281/send/snailmail" \
    -H "Content-Type: application/json" \
    -d "$payload" &
  pids+=($!)
done

for pid in "${pids[@]}"; do
  if ! wait "$pid"; then
    echo "fail" >&2
    exit 1
  fi
done

echo "OK"
