openapi:
  name: api-service-snailmail-sender
  title: SnailMailSender
  version: '@project.version@'

spring:
  application:
    name: api-snailmail-sender
  datasource:
    hikari:
      connection-timeout: 5000
  main:
    banner-mode: 'off'

batch:
  unhandled:
    check-interval: PT10M
    outdated-after: PT1H
    name: unhandledBatch
    lock-at-most-for: PT5M
    initial-delay: PT1M

logbook:
  body-filters:
    # Exclude base64-encoded content from incoming requests.
    json-Path:
      - key: '$.attachments[*].content'
        value: '[base64]'
