openapi:
  name: api-service-snailmail-sender
  title: SnailMailSender
  version: '@project.version@'
spring:
  application:
    name: api-snailmail-sender
  main:
    banner-mode: 'off'
logbook:
  exclusionfilters:
    # Exclude base64-encoded content from incoming requests.
    jsonPath:
      '$.attachments[*].content': '[ base64]'
