openapi:
  name: api-service-snailmail-sender
  title: SnailMailSender
  version: '@project.version@'
spring:
  application:
    name: api-snailmail-sender
  datasource:
    hikari:
      connection-timeout: 5000
  main:
    banner-mode: 'off'
  security:
    oauth2:
      client:
        registration:
          citizen:
            authorization-grant-type: client_credentials
            provider: citizen
batch:
  dangling:
    check-interval: PT10M
    outdated-after: PT1H
    name: danglingBatch
    lock-at-most-for: PT5M
integration:
  citizen:
    connect-timeout: 5
    read-timeout: 30
logbook:
  body-filters:
    # Exclude base64-encoded content from incoming requests.
    json-Path:
      - key: '$.attachments[*].content'
        value: '[base64]'
