openapi:
  name: api-service-snailmail-sender
  title: SnailMailSender
  version: '@project.version@'
spring:
  application:
    name: api-snailmail-sender
  main:
    banner-mode: 'off'
  security:
    oauth2:
      client:
        registration:
          citizen:
            authorization-grant-type: client_credentials
            provider: citizen
integration:
  citizen:
    connect-timeout: 5
    read-timeout: 30
logbook:
  exclusionfilters:
    # Exclude base64-encoded content from incoming requests.
    jsonPath:
      '$.attachments[*].content': '[ base64]'
