openapi:
  name: api-service-snailmail-sender
  title: SnailMailSender
  version: '@project.version@'

spring:
  application:
    name: api-snailmail-sender
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 5000
      transaction-isolation: TRANSACTION_READ_COMMITTED
  main:
    banner-mode: 'off'

batch:
  unhandled:
    cron: 0 */10 * * * *
    name: unhandledBatch
    outdated-after: PT1H
    lock-at-most-for: PT5M
    maximum-execution-time: PT2M

logbook:
  body-filters:
    # Exclude base64-encoded content from incoming requests.
    json-Path:
      - key: '$.attachments[*].content'
        value: '[base64]'
