integration:
  citizen:
    base-url: http://localhost:${wiremock.server.port}/citizen
    client-id: dummy
    client-secret: dummy
    token-uri: http://localhost:${wiremock.server.port}/token
  email-sender:
    base-url: http://localhost:${wiremock.server.port}/emailsender
    client-id: dummy
    client-secret: dummy
    email-address: some@email.com
    sender:
      address: some@email.com
      name: someName
      replyTo: someReplyAddress
    token-uri: http://localhost:${wiremock.server.port}/token
  samba:
    host: localhost
    port: 445
    domain: WORKGROUP
    username: someUsername
    password: somePassword
    share: /someShare/
    connect-timeout: PT5S
    response-timeout: PT10S
