name: Dependabot reviewer

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  review-dependabot-pr:
    uses: Sundsvallskommun/api-shared-workflows/.github/workflows/dependabot_reviewer.yml@main
