name: "Call Dependabot reviewer"

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  call-review-dependabot-pr:
    uses: Sundsvallskommun/shared-workflows/.github/workflows/common-dependabot-reviewer.yml@main
